/**
 * Deterministic OpenAPI generation WITHOUT a manual HTTP server.
 *
 * Builds the real Fastify instance in-process, calls `app.swagger()` after
 * `app.ready()`, and writes the document to `openapi/openapi.json`.
 *
 * No network listener is started. No database connection is opened: the
 * pooled client is created lazily by `pg` and never queried during
 * generation, then closed via `app.close()`.
 */
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { buildApp } from "../../../apps/api/src/app.js";

const here = dirname(fileURLToPath(import.meta.url));
const outFile = join(here, "..", "openapi", "openapi.json");

async function main(): Promise<void> {
  const app = await buildApp({
    config: {
      port: 4001,
      host: "127.0.0.1",
      nodeEnv: "development",
      environment: "development",
      version: "0.1.0",
      databaseUrl: "postgres://localhost:5432/replaybug",
      logLevel: "silent",
      authSecret: "test-secret-0123456789abcdef0123456789",
      webUrl: "http://localhost:3000",
      apiUrl: "http://localhost:4001",
      trustedOrigins: ["http://localhost:3000"],
      ingestMaxBatchEvents: 50,
      ingestMaxBodyBytes: 512 * 1024,
      ingestMaxEventBytes: 128 * 1024,
      ingestRateLimitRequestsPerMinute: 60,
      ingestRateLimitEventsPerMinute: 1000,
      userHmacSecret: undefined,
    },
    checkDatabase: async () => true,
  });
  try {
    await app.ready();
    const document = app.swagger() as Record<string, unknown>;
    const marked = {
      ...document,
      "x-replaybug-generated":
        "DO NOT EDIT BY HAND. Generated by pnpm api:generate from Fastify route schemas. Run pnpm api:generate to refresh.",
    };
    await mkdir(dirname(outFile), { recursive: true });
    await writeFile(outFile, `${JSON.stringify(marked, null, 2)}\n`, "utf8");
    console.log(`OpenAPI written to ${outFile}`);
  } finally {
    await app.close();
  }
}

await main();
