/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health/live": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @enum {unknown} */
              status: "ok";
              /** @enum {unknown} */
              service: "api";
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @enum {unknown} */
              status: "ready";
              checks: {
                /** @enum {unknown} */
                database: "up";
              };
            };
          };
        };
        /** @description Default Response */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @enum {unknown} */
              status: "not-ready";
              checks: {
                /** @enum {unknown} */
                database: "down";
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/meta": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @enum {unknown} */
              service: "api";
              version: string;
              environment: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/{*}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          "*": string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          "*": string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              email: string;
              name: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/workspaces": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              name: string;
              slug: string;
              createdAt: string;
              updatedAt: string;
              /** @enum {string} */
              role: "owner" | "admin" | "member" | "viewer";
            }[];
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            name: string;
            slug?: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              name: string;
              slug: string;
              createdAt: string;
              updatedAt: string;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/workspaces/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              name: string;
              slug: string;
              createdAt: string;
              updatedAt: string;
              /** @enum {string} */
              role: "owner" | "admin" | "member" | "viewer";
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            name?: string;
            slug?: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              name: string;
              slug: string;
              createdAt: string;
              updatedAt: string;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
      };
    };
    trace?: never;
  };
  "/api/v1/workspaces/{id}/members": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              name: string;
              email: string;
              /** @enum {string} */
              role: "owner" | "admin" | "member" | "viewer";
            }[];
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/workspaces/{workspaceId}/projects": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          workspaceId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              workspaceId: string;
              name: string;
              slug: string;
              description?: null | string;
              timezone: string;
              retentionDays: number;
              createdAt: string;
              updatedAt: string;
            }[];
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          workspaceId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            name: string;
            slug?: string;
            description?: string;
            timezone?: string;
            retentionDays?: number;
          };
        };
      };
      responses: {
        /** @description Default Response */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              project: {
                id: string;
                workspaceId: string;
                name: string;
                slug: string;
                description?: null | string;
                timezone: string;
                retentionDays: number;
                createdAt: string;
                updatedAt: string;
              };
              bootstrap: {
                key: string;
                prefix: string;
                projectId: string;
                ingestEndpoint: string;
                ingestEnabled: boolean;
                note: string;
              };
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/projects/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              workspaceId: string;
              name: string;
              slug: string;
              description?: null | string;
              timezone: string;
              retentionDays: number;
              createdAt: string;
              updatedAt: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              deleted: boolean;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            name?: string;
            slug?: string;
            description?: string | null;
            timezone?: string;
            retentionDays?: number;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              workspaceId: string;
              name: string;
              slug: string;
              description?: null | string;
              timezone: string;
              retentionDays: number;
              createdAt: string;
              updatedAt: string;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
      };
    };
    trace?: never;
  };
  "/api/v1/projects/{projectId}/environments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              projectId: string;
              name: string;
              baseUrl?: null | string;
              isDefault: boolean;
              createdAt: string;
              updatedAt: string;
            }[];
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            name: string;
            baseUrl?: string;
            isDefault?: boolean;
          };
        };
      };
      responses: {
        /** @description Default Response */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              projectId: string;
              name: string;
              baseUrl?: null | string;
              isDefault: boolean;
              createdAt: string;
              updatedAt: string;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/environments/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              deleted: boolean;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            name?: string;
            baseUrl?: string | null;
            isDefault?: boolean;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              projectId: string;
              name: string;
              baseUrl?: null | string;
              isDefault: boolean;
              createdAt: string;
              updatedAt: string;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
      };
    };
    trace?: never;
  };
  "/api/v1/projects/{projectId}/origins": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              projectId: string;
              origin: string;
              isEnabled: boolean;
              createdAt: string;
              updatedAt: string;
            }[];
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            origin: string;
            isEnabled?: boolean;
          };
        };
      };
      responses: {
        /** @description Default Response */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              projectId: string;
              origin: string;
              isEnabled: boolean;
              createdAt: string;
              updatedAt: string;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/origins/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              deleted: boolean;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            origin?: string;
            isEnabled?: boolean;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              projectId: string;
              origin: string;
              isEnabled: boolean;
              createdAt: string;
              updatedAt: string;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
      };
    };
    trace?: never;
  };
  "/api/v1/projects/{projectId}/keys": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              projectId: string;
              kind: string;
              name: string;
              prefix: string;
              createdAt: string;
              lastUsedAt?: null | string;
              revokedAt?: null | string;
            }[];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/projects/{id}/keys/public/rotate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              projectId: string;
              kind: string;
              name: string;
              prefix: string;
              key: string;
              createdAt: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/projects/{projectId}/issues": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          status?: "open" | "investigating" | "resolved" | "ignored";
          environment?: string;
          release?: string;
          type?:
            | "exception"
            | "unhandled_rejection"
            | "console_error"
            | "network"
            | "message";
          assigneeId?: string;
          unassigned?: string;
          tag?: string;
          since?: string;
          until?: string;
          q?: string;
          sort?:
            | "last_seen"
            | "first_seen"
            | "occurrence_count"
            | "affected_sessions";
          order?: "asc" | "desc";
          limit?: string;
          cursor?: string;
        };
        header?: never;
        path: {
          projectId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              items: {
                id: string;
                projectId: string;
                type: string;
                title: string;
                normalizedMessage: string;
                status: string;
                severity: string;
                assignee: {
                  id: string;
                  email: string;
                  name: string;
                  image?: null | string;
                  emailVerified: boolean;
                } | null;
                firstSeenAt: string;
                lastSeenAt: string;
                resolvedAt: null | string;
                firstRelease: null | string;
                lastRelease: null | string;
                occurrenceCount: number;
                affectedSessionCount: number;
                tags: {
                  id: string;
                  name: string;
                  slug: string;
                }[];
                createdAt: string;
                updatedAt: string;
              }[];
              nextCursor?: string;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/projects/{projectId}/metrics": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          range?: "24h" | "7d" | "30d";
        };
        header?: never;
        path: {
          projectId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              range: string;
              bucketStart: string;
              bucketEnd: string;
              bucketSize: string;
              unresolvedCount: number;
              newIssueCount: number;
              occurrenceCount: number;
              affectedSessionCount: number;
              regressionCount: number;
              topIssues: {
                issueId: string;
                title: string;
                occurrences: number;
              }[];
              overTime: {
                bucketStart: string;
                occurrences: number;
                newIssues: number;
              }[];
              byEnvironment: {
                key: string;
                occurrences: number;
              }[];
              byRelease: {
                key: string;
                occurrences: number;
              }[];
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/issues/{issueId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          issueId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              projectId: string;
              type: string;
              title: string;
              normalizedMessage: string;
              status: string;
              severity: string;
              assignee: {
                id: string;
                email: string;
                name: string;
                image?: null | string;
                emailVerified: boolean;
              } | null;
              firstSeenAt: string;
              lastSeenAt: string;
              resolvedAt: null | string;
              firstRelease: null | string;
              lastRelease: null | string;
              occurrenceCount: number;
              affectedSessionCount: number;
              tags: {
                id: string;
                name: string;
                slug: string;
              }[];
              createdAt: string;
              updatedAt: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/issues/{issueId}/occurrences": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          limit?: string;
          cursor?: string;
        };
        header?: never;
        path: {
          issueId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              items: {
                eventId: string;
                sessionId: string;
                occurredAt: string;
                receivedAt: string;
                environment: string;
                release: null | string;
                pageUrl: null | string;
                eventType: string;
                processingState: string;
              }[];
              nextCursor?: string;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/events/{eventId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          eventId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              eventId: string;
              sessionId: string;
              issueId: null | string;
              eventType: string;
              occurredAt: string;
              receivedAt: string;
              environment: string;
              release: null | string;
              pageUrl: null | string;
              processingState: string;
              data:
                | {
                    values: {
                      type: string;
                      value: string;
                      stacktrace?: {
                        frames: {
                          filename?: string;
                          function?: string;
                          lineno?: number;
                          colno?: number;
                          inApp?: boolean;
                        }[];
                      };
                    }[];
                  }
                | {
                    reason: string;
                  }
                | {
                    args: string[];
                  }
                | {
                    url: string;
                    method: string;
                    statusCode: number | null;
                    durationMs: number;
                    failureType?: string;
                  }
                | {
                    message: string;
                    level: string;
                  }
                | {
                    fromUrl?: string | null;
                    toUrl: string;
                    navigationType: string;
                  }
                | {
                    locatorCandidates: {
                      type: string;
                      value: string;
                      confidence: number;
                    }[];
                    elementTag: string;
                    elementRole?: string;
                    accessibleName?: string;
                    route?: string;
                  }
                | {
                    inputType: string;
                    inputName?: string;
                    hasValue: boolean;
                  }
                | {
                    category: string;
                    message: string;
                    level: string;
                  }
                | {
                    sdkName: string;
                    sdkVersion: string;
                    event: string;
                  };
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/issues/{issueId}/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          issueId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /** @enum {string} */
            status: "open" | "investigating" | "resolved" | "ignored";
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              projectId: string;
              type: string;
              title: string;
              normalizedMessage: string;
              status: string;
              severity: string;
              assignee: {
                id: string;
                email: string;
                name: string;
                image?: null | string;
                emailVerified: boolean;
              } | null;
              firstSeenAt: string;
              lastSeenAt: string;
              resolvedAt: null | string;
              firstRelease: null | string;
              lastRelease: null | string;
              occurrenceCount: number;
              affectedSessionCount: number;
              tags: {
                id: string;
                name: string;
                slug: string;
              }[];
              createdAt: string;
              updatedAt: string;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
      };
    };
    trace?: never;
  };
  "/api/v1/issues/{issueId}/assignee": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          issueId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            userId: string | null;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              projectId: string;
              type: string;
              title: string;
              normalizedMessage: string;
              status: string;
              severity: string;
              assignee: {
                id: string;
                email: string;
                name: string;
                image?: null | string;
                emailVerified: boolean;
              } | null;
              firstSeenAt: string;
              lastSeenAt: string;
              resolvedAt: null | string;
              firstRelease: null | string;
              lastRelease: null | string;
              occurrenceCount: number;
              affectedSessionCount: number;
              tags: {
                id: string;
                name: string;
                slug: string;
              }[];
              createdAt: string;
              updatedAt: string;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
      };
    };
    trace?: never;
  };
  "/api/v1/projects/{projectId}/tags": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              projectId: string;
              name: string;
              slug: string;
              createdAt: string;
            }[];
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            name: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              projectId: string;
              name: string;
              slug: string;
              createdAt: string;
            };
          };
        };
        /** @description Default Response */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              projectId: string;
              name: string;
              slug: string;
              createdAt: string;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/issues/{issueId}/tags/{tagId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          issueId: string;
          tagId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              projectId: string;
              name: string;
              slug: string;
              createdAt: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
      };
    };
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          issueId: string;
          tagId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              removed: boolean;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/issues/{issueId}/comments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          limit?: string;
          cursor?: string;
        };
        header?: never;
        path: {
          issueId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              items: {
                id: string;
                issueId: string;
                author: {
                  id: string;
                  email: string;
                  name: string;
                  image?: null | string;
                  emailVerified: boolean;
                };
                bodyMarkdown: string;
                createdAt: string;
                updatedAt: string;
              }[];
              nextCursor?: string;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          issueId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            body: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              issueId: string;
              author: {
                id: string;
                email: string;
                name: string;
                image?: null | string;
                emailVerified: boolean;
              };
              bodyMarkdown: string;
              createdAt: string;
              updatedAt: string;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/issues/{issueId}/comments/{commentId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          issueId: string;
          commentId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            body: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              issueId: string;
              author: {
                id: string;
                email: string;
                name: string;
                image?: null | string;
                emailVerified: boolean;
              };
              bodyMarkdown: string;
              createdAt: string;
              updatedAt: string;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
      };
    };
    trace?: never;
  };
  "/api/v1/issues/{issueId}/activity": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          limit?: string;
          cursor?: string;
        };
        header?: never;
        path: {
          issueId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              items: {
                id: string;
                issueId: string;
                type: string;
                actor: {
                  id: string;
                  email: string;
                  name: string;
                  image?: null | string;
                  emailVerified: boolean;
                } | null;
                metadata: {
                  [key: string]: unknown;
                };
                createdAt: string;
              }[];
              nextCursor?: string;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/notifications": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          unreadOnly?: string;
          limit?: string;
          cursor?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              items: {
                id: string;
                type: string;
                title: string;
                body: string;
                projectId: null | string;
                issueId: null | string;
                readAt: null | string;
                createdAt: string;
              }[];
              nextCursor?: string;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/notifications/unread-count": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              unreadCount: number;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/notifications/{id}/read": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              type: string;
              title: string;
              body: string;
              projectId: null | string;
              issueId: null | string;
              readAt: null | string;
              createdAt: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
      };
    };
    trace?: never;
  };
  "/api/v1/notifications/read-all": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              marked: number;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/projects/{projectId}/events/stream": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "text/event-stream": string;
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "text/event-stream": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "text/event-stream": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "text/event-stream": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/projects/{projectId}/sessions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          environment?: string;
          release?: string;
          since?: string;
          until?: string;
          hasErrors?: string;
          order?: "asc" | "desc";
          limit?: string;
          cursor?: string;
        };
        header?: never;
        path: {
          projectId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              items: {
                id: string;
                projectId: string;
                environment: string;
                release: null | string;
                startedAt: string;
                lastSeenAt: string;
                initialUrl: string;
                browserName: null | string;
                browserVersion: null | string;
                osName: null | string;
                osVersion: null | string;
                deviceType: null | string;
                viewportWidth: null | number;
                viewportHeight: null | number;
                sdkVersion: string;
              }[];
              nextCursor?: string;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/sessions/{sessionId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          sessionId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              id: string;
              projectId: string;
              environment: string;
              release: null | string;
              startedAt: string;
              lastSeenAt: string;
              initialUrl: string;
              browserName: null | string;
              browserVersion: null | string;
              osName: null | string;
              osVersion: null | string;
              deviceType: null | string;
              viewportWidth: null | number;
              viewportHeight: null | number;
              sdkVersion: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/sessions/{sessionId}/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          limit?: string;
          cursor?: string;
        };
        header?: never;
        path: {
          sessionId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              items: {
                id: string;
                sequenceNumber: number;
                eventType: string;
                occurredAt: string;
                receivedAt: string;
                environment: string;
                release: null | string;
                pageUrl: null | string;
                processingState: string;
                summary: string;
              }[];
              nextCursor?: string;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/events/{eventId}/timeline-context": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          before?: string;
          after?: string;
        };
        header?: never;
        path: {
          eventId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              sessionId: string;
              anchor: {
                id: string;
                sequenceNumber: number;
                eventType: string;
                occurredAt: string;
                receivedAt: string;
                environment: string;
                release: null | string;
                pageUrl: null | string;
                processingState: string;
                summary: string;
              };
              before: {
                id: string;
                sequenceNumber: number;
                eventType: string;
                occurredAt: string;
                receivedAt: string;
                environment: string;
                release: null | string;
                pageUrl: null | string;
                processingState: string;
                summary: string;
              }[];
              after: {
                id: string;
                sequenceNumber: number;
                eventType: string;
                occurredAt: string;
                receivedAt: string;
                environment: string;
                release: null | string;
                pageUrl: null | string;
                processingState: string;
                summary: string;
              }[];
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              code: string;
              message: string;
              requestId: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ingest/v1/batch": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            protocol_version: number;
            sdk_name: string;
            sdk_version: string;
            session: Record<string, never>;
            events: unknown[];
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              accepted: number;
              duplicate: number;
              rejected: number;
              requestId: string;
            };
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @enum {string} */
              code:
                | "INVALID_PUBLIC_KEY"
                | "REVOKED_PUBLIC_KEY"
                | "DISALLOWED_ORIGIN"
                | "UNSUPPORTED_PROTOCOL_VERSION"
                | "MALFORMED_PAYLOAD"
                | "PAYLOAD_TOO_LARGE"
                | "RATE_LIMITED"
                | "UNSUPPORTED_EVENT_TYPE";
              message: string;
              requestId: string;
              details?: Record<string, never>;
            };
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @enum {string} */
              code:
                | "INVALID_PUBLIC_KEY"
                | "REVOKED_PUBLIC_KEY"
                | "DISALLOWED_ORIGIN"
                | "UNSUPPORTED_PROTOCOL_VERSION"
                | "MALFORMED_PAYLOAD"
                | "PAYLOAD_TOO_LARGE"
                | "RATE_LIMITED"
                | "UNSUPPORTED_EVENT_TYPE";
              message: string;
              requestId: string;
              details?: Record<string, never>;
            };
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @enum {string} */
              code:
                | "INVALID_PUBLIC_KEY"
                | "REVOKED_PUBLIC_KEY"
                | "DISALLOWED_ORIGIN"
                | "UNSUPPORTED_PROTOCOL_VERSION"
                | "MALFORMED_PAYLOAD"
                | "PAYLOAD_TOO_LARGE"
                | "RATE_LIMITED"
                | "UNSUPPORTED_EVENT_TYPE";
              message: string;
              requestId: string;
              details?: Record<string, never>;
            };
          };
        };
        /** @description Default Response */
        429: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @enum {string} */
              code:
                | "INVALID_PUBLIC_KEY"
                | "REVOKED_PUBLIC_KEY"
                | "DISALLOWED_ORIGIN"
                | "UNSUPPORTED_PROTOCOL_VERSION"
                | "MALFORMED_PAYLOAD"
                | "PAYLOAD_TOO_LARGE"
                | "RATE_LIMITED"
                | "UNSUPPORTED_EVENT_TYPE";
              message: string;
              requestId: string;
              details?: Record<string, never>;
            };
          };
        };
      };
    };
    delete?: never;
    options: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/demo/500-endpoint": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
